# Basic travis script
language: objective-c  #1
osx_image: xcode7.3 #2
xcode_workspace: Xcode8CIiOSExampleApp.xcworkspace #3
xcode_scheme: Xcode8CIiOSExampleApp #4
xcode_sdk: iphonesimulator9.2 #5
#xcode_sdk: macosx10.11

#language: objective-c
#osx_image: xcode8
#before_install:
#- brew update
#- brew install carthage || brew outdated carthage || brew upgrade carthage
#install:
#- carthage bootstrap
#branches:
#only:
#- master
#-
#script:
#- set -o pipefail && xcodebuild -workspace Xcode8CIiOSExampleApp.xcworkspace -scheme Xcode8CIiOSExampleApp -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' build test | xcpretty --color


