---
before_install:
- "gem install xcpretty"
language: objective-c
osx_image: xcode8
script:
- "xcodebuild -workspace $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -configuration \"$APP_BUILD_ENV\" OBJROOT=\"$PWD/build\" SYMROOT=\"$PWD/build\" ONLY_ACTIVE_ARCH=NO | xcpretty -c"
xcode_scheme: Xcode8CIiOSExampleApp
xcode_sdk: iphonesimulator10.0
xcode_workspace: Xcode8CIiOSExampleApp.xcworkspace
